version: '3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0-arm64
    container_name: es01
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
      - ./elastic_data_backup:/opt/elasticsearch/backup
      - ./book_backup:/tmp/es-repo/book_backup
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300